server:
	port: 8082

spring:
	datasource:
		url: jdbc:mysql://localhost:3306/order_service
		username: root
		password: Thanuja123
		driver-class-name: com.mysql.cj.jdbc.Driver
	jpa:
		hibernate:
			ddl-auto: update
		show-sql: true
		properties:
			hibernate:
				format_sql: true
				dialect: org.hibernate.dialect.MySQLDialect

eureka:
	client:
		serviceUrl:
			defaultZone: http://localhost:8761/eureka/
	instance:
		preferIpAddress: true

management:
	endpoints:
		web:
			exposure:
				include: "*"
	tracing:
		sampling:
			probability: 1.0

resilience4j:
	circuitbreaker:
		instances:
			productService:
				registerHealthIndicator: true
				slidingWindowSize: 10
				permittedNumberOfCallsInHalfOpenState: 3
				slidingWindowType: COUNT_BASED
				minimumNumberOfCalls: 5
				waitDurationInOpenState: 5s
				failureRateThreshold: 50